version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: pg-db
    restart: always
    environment:
      POSTGRES_DB: myappdb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend

  redis:
    image: redis:7
    container_name: redis-cache
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data
    networks:
      - backend

  minio:
    image: minio/minio:latest
    container_name: minio-server
    restart: always
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000" # API
      - "9001:9001" # Console
    volumes:
      - miniodata:/data
    networks:
      - backend

volumes:
  pgdata:
  redisdata:
  miniodata:

networks:
  backend:
    driver: bridge
